kind: Service
apiVersion: v1
metadata:
  name: porter-nginx-svc
  annotations:
    lb.kubesphere.io/v1alpha1: porter
    protocol.porter.kubesphere.io/v1alpha1: bgp
    eip.porter.kubesphere.io/v1alpha2: porter-bgp-eip
spec:
  selector:
    run: my-nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster
