- name: set swap off
  shell: swapoff -a && sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: set firewalld off
  shell: systemctl stop firewalld && systemctl disable firewalld

- name: set timezone to  Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: present chronyd service
  yum: name=chronyd state=present

- name: set time now
  shell: sed -i 's/2.centos.pool.ntp.org/ntp1.aliyun.com/g' /etc/chrony.conf
  ignore_errors: yes

- name: sync time now
  service: name=chronyd  state=restarted
