- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: net.ipv4.tcp_tw_recycle
    value: '0'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: vm.panic_on_oom
    value: '0'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: '8192'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '1048576'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: fs.file-max
    value: '52706963'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: fs.nr_open
    value: '52706963'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

- ansible.posix.sysctl:
    name: net.netfilter.nf_conntrack_max
    value: '2310720'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: yes
    ignoreerrors: yes

