- name: mkdir   /var/log/journal
  file: path=/var/log/journal  state=directory

- name: mkdir /etc/systemd/journald.conf.d
  file: path=/etc/systemd/journald.conf.d  state=directory

- name: copy journal config file
  copy: src=../files/99-prophet.conf dest=/etc/systemd/journald.conf.d/99-prophet.conf

- name: "生效journal config file"
  service: name=systemd-journald state=restarted
