- name: install docker
  yum: name=yum-utils,device-mapper-persistent-data,lvm2

- name: install containerd.io
  shell: yum -y install https://mirrors.aliyun.com/docker-ce/linux/centos/7/x86_64/stable/Packages/containerd.io-1.3.7-3.1.el7.x86_64.rpm

- name: install docker-ce
  shell: yum -y install docker-ce

- name: create /etc/docker dir
  file: path=/etc/docker  state=directory

- name: copy docker daemon.json
  copy: src=../files/daemon.json dest=/etc/docker/daemon.json

- name: mkdir -p /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d  state=directory

- name: start docker
  shell: systemctl daemon-reload && systemctl restart docker && systemctl enable docker
