- name: install device-mapper-persistent-data lvm2
  yum: name=yum-utils,device-mapper-persistent-data,lvm2

- name: install containerd.io
  shell: yum -y install https://mirrors.aliyun.com/docker-ce/linux/centos/7/x86_64/stable/Packages/containerd.io-1.3.7-3.1.el7.x86_64.rpm

- name: install docker-ce
  shell: yum -y install docker-ce

- name: create /etc/docker dir
  file: path=/etc/docker  state=directory

- name: copy docker daemon.json
  copy: src=../files/daemon.json dest=/etc/docker/daemon.json

- name: mkdir -p /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d  state=directory

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: start docker
  systemd:  name=docker  state=started  enabled=yes
