- name: install device-mapper-persistent-data lvm2
  yum: name=yum-utils,device-mapper-persistent-data,lvm2

- name: install docker-ce
  yum: name=docker-ce-19.03.15-3.el7,docker-ce-19.03.15-3.el7,containerd.io

- name: create /etc/docker dir
  file: path=/etc/docker  state=directory

- name: copy docker daemon.json
  copy: src=../files/daemon.json dest=/etc/docker/daemon.json

- name: mkdir -p /etc/systemd/system/docker.service.d
  file: path=/etc/systemd/system/docker.service.d  state=directory

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: start docker
  systemd:  name=docker  state=started  enabled=yes
